# Generated by Django 5.2.11 on 2026-03-14 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slugname', models.CharField(max_length=255, unique=True)),
                ('company_url', models.URLField()),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_html', models.BinaryField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.BigIntegerField(unique=True)),
                ('title', models.TextField()),
                ('location', models.TextField(null=True)),
                ('job_url', models.URLField(max_length=500)),
                ('description', models.TextField(null=True)),
                ('posted_at', models.DateTimeField(null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('LinkedIn', 'LinkedIn')], default='linkedin', max_length=50)),
                ('payload', models.JSONField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkedIn_jobs.company')),
                ('raw_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='linkedIn_jobs.jobrawdata')),
            ],
        ),
    ]
