# Generated by Django 5.2.11 on 2026-04-08 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedIn_jobs', '0001_created_jobs_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('technical_skills', 'Technical Skills'), ('soft_skills', 'Soft Skills'), ('business_skills', 'Business Skills'), ('domain_skills', 'Domain Skills'), ('operational_skills', 'Operational Skills')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='max_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='normalized_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkedIn_jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkedIn_jobs.skill')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkedIn_jobs.skillcategory')),
            ],
            options={
                'unique_together': {('job', 'skill', 'category')},
            },
        ),
    ]
