# Generated by Django 5.2.11 on 2026-04-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedIn_jobs', '0002_added_job_skill_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='llm_processed',
            field=models.BooleanField(default=False),
        ),
    ]
