# Generated by Django 5.2.11 on 2026-04-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedIn_jobs', '0003_added_boolean_field_in_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='normalized_title',
        ),
        migrations.AddField(
            model_name='job',
            name='primary_tech',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='role_category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
