# Generated by Django 5.2.11 on 2026-04-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedIn_jobs', '0004_remove_job_normalized_title_job_primary_tech_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobskill',
            unique_together={('job', 'skill')},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical_skills', 'Technical Skills'), ('soft_skills', 'Soft Skills'), ('business_skills', 'Business Skills'), ('domain_skills', 'Domain Skills'), ('operational_skills', 'Operational Skills'), ('others', 'Others')], default='others', max_length=50),
        ),
        migrations.RemoveField(
            model_name='jobskill',
            name='category',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
    ]
