# Generated by Django 5.2.11 on 2026-04-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedIn_jobs', '0005_skill_category_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
