# Generated by Django 5.2.11 on 2026-04-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedIn_jobs', '0006_skill_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='embedding',
        ),
        migrations.AddField(
            model_name='skill',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
