"""
Django settings for mb_backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-04*fp#rg&n)g+q)$(_d4-looswhd3f6iyv%i1$bj0@fcdj7@)w'

ALLOWED_HOSTS = ["127.0.0.1", "192.168.68.118", 'localhost', 'mb-business-backend.onrender.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.messages',

    'django_extensions',
    'django_cron',
    'django_celery_beat',

    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

    #Apps
    'authentication',
    'livestock',
    'Expenditure',
    'CustomersApp'

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'mb_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mb_backend.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    'http://192.168.1.23:5173',
    'http://localhost:5173',
    'https://mb-admin-frontend.netlify.app'
]

CORS_ALLOW_CREDENTIALS=True

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "authentication.UserModel"


# Media files (User uploads, images, etc.)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Email Sending configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'stefenwarner13@gmail.com'
EMAIL_HOST_PASSWORD = 'iyutbwcpmhehhmuc'
DEFAULT_FROM_EMAIL = 'stefenwarner13@gmail.com'


LOGS_PATH = os.path.join(BASE_DIR, 'logs')
FILE_SIZE = 1024 * 1024 * 5  # 5 MB
BACKUP_COUNT = 2

PRIMARY_MAIL = 'ramumeegada18@gmail.com'

AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_BUCKET_NAME = 'mb-backend-s3-bucket'
AWS_REGION = 'ap-south-1'
OPENAI_API_KEY = config('OPENAI_API_KEY')

SEND_MAIL_OVER_QUERIES = True

ADMINS = [
    ('Ram', 'ramumeegada18@gmail.com'),
    ('Lahari', 'laharimeegada9@gmail.com'),
    ('Jaitej', 'jaitejmeegada@gmail.com'),
    ('Vamsi', 'vamsisunny7013@gmail.com'),
    ('Deshuk', 'deshukyadav3@gmail.com')
]

DJANGO_CRON_OUTPUT_ERRORS = True

CRON_CLASSES = [
    'CustomersApp.crons.GenerateMonthlyPaymentsCron',
    'CustomersApp.crons.CreateDailyOrdersCron',
    'infra.crons.SaveBackUpOfProdDbCron'
]

if not os.path.exists(LOGS_PATH):
    os.makedirs(LOGS_PATH)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] [{asctime}] [{module}] [{process:d}] [{thread:d}] ==> {message}\n",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_debug_false"],
        },
        "auth_handler": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_PATH, "auth.log"),
            "maxBytes": FILE_SIZE,
            "backupCount": BACKUP_COUNT,
            "formatter": "verbose",
        },
        "common_handler": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_PATH, "common.log"),
            "maxBytes": FILE_SIZE,
            "backupCount": BACKUP_COUNT,
            "formatter": "verbose",
        },
        "expenditure_handler": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_PATH, "expenditure.log"),
            "maxBytes": FILE_SIZE,
            "backupCount": BACKUP_COUNT,
            "formatter": "verbose",
        },
        "customers_handler": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_PATH, "customers.log"),
            "maxBytes": FILE_SIZE,
            "backupCount": BACKUP_COUNT,
            "formatter": "verbose",
        },
        "analytics_handler": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_PATH, "analytics.log"),
            "maxBytes": FILE_SIZE,
            "backupCount": BACKUP_COUNT,
            "formatter": "verbose",
        },
        "crons_handler": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_PATH, "crons.log"),
            "maxBytes": FILE_SIZE,
            "backupCount": BACKUP_COUNT,
            "formatter": "verbose",
        },
        "bujjiAI_handler": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOGS_PATH, "bujjiAI.log"),
            "maxBytes": FILE_SIZE,
            "backupCount": BACKUP_COUNT,
            "formatter": "verbose",
        }
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "propagate": True,
        },
        # "django.request": {
        #     "handlers": ["mail_admins", "common_handler"],
        #     "level": "ERROR",
        #     "propagate": False,
        # },
        "Common": {
            "handlers": ["common_handler"],
            "level": "INFO",
            "propagate": False,
        },
        "Authentication": {
            "handlers": ["auth_handler"],
            "level": "DEBUG",
            "propagate": False,
        },
        "Expenditure": {
            "handlers": ["expenditure_handler"],
            "level": "DEBUG",
            "propagate": False,
        },
        "Customers": {
            "handlers": ["customers_handler"],
            "level": "DEBUG",
            "propagate": False,
        },
        "Analytics": {
            "handlers": ["analytics_handler"],
            "level": "DEBUG",
            "propagate": False,
        },
        "Crons": {
            "handlers": ["crons_handler"],
            "level": "DEBUG",
            "propagate": False,
        },
        'django_cron': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'BujjiAI': {
            'handlers': ['bujjiAI_handler'],
            'level': 'DEBUG',
            'propagate': False,
        }
    },
}


NEWS_API = "fc5bf9c91f6c4e699bddffe2a847d13e"