# Generated by Django 5.1.7 on 2025-04-03 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_usermodel_groups_usermodel_user_permissions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='users',
        ),
    ]
