# Generated by Django 5.1.7 on 2025-04-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_usermodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone_num',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Customer'), (3, 'Delivery agent')], null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
