# Generated by Django 5.1.7 on 2025-05-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0001_added_customer_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='is_morning_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
