# Generated by Django 5.1.7 on 2025-05-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0002_ordersmodel_is_morning_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='total_amount',
        ),
    ]
