# Generated by Django 5.1.7 on 2025-05-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0004_customersubscriptionmodel_delivery_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubscriptionmodel',
            name='price_at_subscription',
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='price_at_order',
            field=models.FloatField(default=0, verbose_name='Price at order'),
            preserve_default=False,
        ),
    ]
