# Generated by Django 5.1.7 on 2025-05-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0005_remove_customersubscriptionmodel_price_at_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersubscriptionmodel',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
