# Generated by Django 5.1.7 on 2025-05-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0006_customersubscriptionmodel_is_paused'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersmodel',
            old_name='subscription',
            new_name='customer',
        ),
    ]
