# Generated by Django 5.1.7 on 2025-06-11 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0007_rename_subscription_ordersmodel_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomersApp.customersubscriptionmodel', verbose_name='Customer Subscription'),
        ),
        migrations.AddConstraint(
            model_name='ordersmodel',
            constraint=models.UniqueConstraint(fields=('customer', 'is_morning_delivery', 'schedule_date'), name='unique_order'),
        ),
    ]
