# Generated by Django 5.1.7 on 2025-06-13 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0008_alter_ordersmodel_customer_ordersmodel_unique_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Use any date in the month, e.g. 2025-06-01')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CustomersApp.customersubscriptionmodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'month'), name='unique_monthly_payment')],
            },
        ),
    ]
