# Generated by Django 5.1.7 on 2025-06-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0009_monthlypaymentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubscriptionmodel',
            name='is_paused',
        ),
    ]
