# Generated by Django 5.1.7 on 2025-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0010_remove_customersubscriptionmodel_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplanmodel',
            name='evening_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Evening price'),
        ),
        migrations.AddField(
            model_name='subscriptionplanmodel',
            name='evening_quantity',
            field=models.IntegerField(blank=True, choices=[(250, 250), (500, 500), (750, 750), (1000, 1000), (1250, 1250), (1500, 1500), (2000, 2000)], null=True, verbose_name='Evening quantity'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanmodel',
            name='price',
            field=models.FloatField(verbose_name='Morning price'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanmodel',
            name='quantity',
            field=models.IntegerField(choices=[(250, 250), (500, 500), (750, 750), (1000, 1000), (1250, 1250), (1500, 1500), (2000, 2000)], verbose_name='Morning quantity'),
        ),
    ]
