# Generated by Django 5.1.7 on 2025-06-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0011_subscriptionplanmodel_evening_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplanmodel',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Morning price'),
        ),
        migrations.AlterField(
            model_name='subscriptionplanmodel',
            name='quantity',
            field=models.IntegerField(blank=True, choices=[(250, 250), (500, 500), (750, 750), (1000, 1000), (1250, 1250), (1500, 1500), (2000, 2000)], null=True, verbose_name='Morning quantity'),
        ),
    ]
