# Generated by Django 5.1.7 on 2025-06-16 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0012_alter_subscriptionplanmodel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersubscriptionmodel',
            name='delivery_schedule',
        ),
    ]
