# Generated by Django 5.1.7 on 2025-06-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0013_remove_customersubscriptionmodel_delivery_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplanmodel',
            name='schedule',
            field=models.IntegerField(choices=[(1, 'Morning Only'), (2, 'Evening only'), (3, 'Both')], default=1),
        ),
    ]
