# Generated by Django 5.1.7 on 2025-07-07 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0014_subscriptionplanmodel_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypaymentmodel',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_payments', to='CustomersApp.customersubscriptionmodel'),
        ),
    ]
