# Generated by Django 5.1.7 on 2025-04-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditurecategorymodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
