# Generated by Django 5.1.7 on 2025-03-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expendituremodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
