# Generated by Django 5.1.7 on 2025-04-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0002_alter_expendituremodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expendituremodel',
            name='category',
            field=models.CharField(choices=[('feed', 'Feed'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20),
        ),
    ]
