# Generated by Django 5.1.7 on 2025-04-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0003_alter_expendituremodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditurecategorymodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
