# Generated by Django 5.1.7 on 2025-04-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0003_alter_expendituremodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditurecategorymodel',
            name='short_name',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
