# Generated by Django 5.1.7 on 2025-08-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0004_expenditurecategorymodel_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expendituremodel',
            name='user',
        ),
    ]
