# Generated by Django 5.2.11 on 2026-04-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('skills_extraction', 'Skills Extraction')], max_length=50)),
                ('model', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
