# Generated by Django 5.2.11 on 2026-04-28 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujjiAI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='Prompt Tokens')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='Completion Tokens')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Total Tokens')),
                ('cached_tokens', models.IntegerField(default=0, verbose_name='Cached Tokens')),
                ('cost', models.FloatField(verbose_name="Cost (USD)")),
                ('request_type', models.CharField(choices=[(1, 'Skills Extraction'), (2, 'Chat')], max_length=50, verbose_name='Request Type')),
                ('latency_ms', models.IntegerField(blank=True, null=True, verbose_name='Latency (ms)')),
                ('is_success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OpenAIUsage',
        ),
    ]
