# Generated by Django 5.2.11 on 2026-04-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BujjiAI', '0002_llmusage_delete_openaiusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmusage',
            name='request_type',
            field=models.IntegerField(choices=[(1, 'Skills Extraction'), (2, 'Chat')], verbose_name='Request Type'),
        ),
    ]
