# Generated by Django 5.1.7 on 2025-03-15 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_usermodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_stock_id', models.CharField(unique=True)),
                ('breed', models.CharField(choices=[('Bhadawari', 'Bhadawari'), ('Jaffarabadi', 'Jaffarabadi'), ('Marathwadi', 'Marathwadi'), ('Mehsana', 'Mehsana'), ('Murrah', 'Murrah'), ('Nagpuri', 'Nagpuri'), ('Nili Ravi', 'Nili Ravi'), ('Pandharpuri', 'Pandharpuri'), ('Surti', 'Surti'), ('Toda', 'Toda'), ('Banni', 'Banni'), ('Chilika', 'Chilika'), ('Kalahandi', 'Kalahandi'), ('Luit (Swamp)', 'Luit (Swamp)'), ('Bargur', 'Bargur'), ('Chhattisgarhi', 'Chhattisgarhi'), ('Gojri', 'Gojri'), ('Dharwadi', 'Dharwadi'), ('Manda', 'Manda'), ('Purnathadi', 'Purnathadi')])),
                ('is_pregnant', models.BooleanField(default=False)),
                ('last_calvation_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('lactation_month', models.IntegerField()),
                ('purchase_price', models.FloatField()),
                ('milk_capacity', models.FloatField()),
                ('parity', models.IntegerField()),
                ('seller_details', models.TextField(blank=True)),
                ('qualities', models.TextField()),
                ('food_habits', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.usermodel')),
            ],
        ),
    ]
