# Generated by Django 5.1.7 on 2025-03-16 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_alter_livestockmodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livestockmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='livestockmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livestockmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
