# Generated by Django 5.1.7 on 2025-03-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_livestockmodel_created_at_livestockmodel_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockmodel',
            name='age',
        ),
    ]
