# Generated by Django 5.1.7 on 2025-03-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_remove_livestockmodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockmodel',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
