# Generated by Django 5.1.7 on 2025-03-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_livestockmodel_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestockmodel',
            old_name='age',
            new_name='date_of_birth',
        ),
    ]
