# Generated by Django 5.1.7 on 2025-03-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0006_rename_age_livestockmodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestockmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='livestockmodel',
            table='Live Stocks',
        ),
    ]
