# Generated by Django 5.1.7 on 2025-03-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0007_alter_livestockmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockmodel',
            name='food_habits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='livestockmodel',
            name='qualities',
            field=models.TextField(blank=True),
        ),
    ]
