# Generated by Django 5.1.7 on 2025-03-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0008_alter_livestockmodel_food_habits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestockmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images'),
        ),
    ]
