# Generated by Django 5.1.7 on 2025-03-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0009_livestockmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
