# Generated by Django 5.1.7 on 2025-03-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0010_alter_livestockmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockmodel',
            name='qualities',
            field=models.TextField(),
        ),
    ]
