# Generated by Django 5.1.7 on 2025-03-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0013_alter_livestockmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockmodel',
            name='live_stock_id',
        ),
    ]
