# Generated by Django 5.1.7 on 2025-03-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0014_remove_livestockmodel_live_stock_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='livestockmodel',
            table='Live Stock',
        ),
    ]
