# Generated by Django 5.1.7 on 2025-04-03 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0015_alter_livestockmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='livestockmodel',
            table='Live Stock Table',
        ),
    ]
