# Generated by Django 5.1.7 on 2025-05-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0017_added_product_and_animal_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='unit',
            field=models.CharField(choices=[('gm', 'grams'), ('lt', 'litres')], default='gm', max_length=10),
            preserve_default=False,
        ),
    ]
