# Generated by Django 5.1.7 on 2025-08-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0018_added_unit_field_for_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestockmodel',
            name='user',
        ),
    ]
